GET http://localhost:3000/test

###
GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/4

###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "description": 1
}

###
PATCH http://localhost:3000/categories/6
Content-Type: application/json

{
    "description": "Descrição atualizada"
}

###
DELETE http://localhost:3000/categories/4